[package]
name = "aoc2020_rust"
version = "0.1.0"
authors = ["CrepeGoat <awqatty.b@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-complex = "0.3"  # Day 12 part 1
itertools = "0.9.0"  # Day 17